// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkzqnrhsabplxhzmxbwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrenFucmhzYWJwbHhoem14YndtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NTk0MzQsImV4cCI6MjA1OTMzNTQzNH0.w0WYDPcLaCoWz5zZqgkfjspopbd_9COEs8go5WPCK7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);